# Generated by Django 5.0.3 on 2024-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("video_id", models.CharField(max_length=50, unique=True)),
                ("channel_id", models.CharField(max_length=50)),
                ("published_at", models.DateTimeField()),
                ("thumbnail_url", models.URLField()),
                ("channel_title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "video",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["video_id", "-published_at"],
                        name="video_video_i_76ce6d_idx",
                    ),
                    models.Index(
                        fields=["channel_id", "-published_at"],
                        name="video_channel_9b4170_idx",
                    ),
                ],
            },
        ),
    ]
