# Generated by Django 5.0.3 on 2024-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="video",
            constraint=models.UniqueConstraint(
                fields=("video_id", "channel_id"), name="unique_video"
            ),
        ),
    ]
